### PR TITLE
Add Basic Complementary Channel Support to PWM

### PR DESCRIPTION
**Pull request by AdinAck**
## Motivation
Issue #162 created by *myself*.
TL;DR: PWM module did not support complementary channels, it should.

## Change(s) Description
- Add CHxN pins, (traits?), and structs and whatnot
- Set `OSSR` and `CCxNE` registers accordingly

## Testing
I have only confirmed it works on CH1/CH1N, but I don't see why it wouldn't work on the others.

## Warning
This is my first time using Rust.

### CODE REVIEW

**Review by therealprof — COMMENTED** [review]
Nice! Could you turn the 2 CHANGELOG lines into one and address the rustfmt failure, please?

**Comment by AdinAck** [comment]
I think I did it? It isn't running the format check but if I understood the failure output correctly it should pass now.

**Comment by AdinAck** [comment]
rust-fmt doesn't mess around!

I've tried again.

**Review by therealprof — APPROVED** [review]
LGTM

bors r+

**Pull request merged**
