### PR TITLE
PWM support

### LINKED ISSUE #26: PWM support
I started implementing PWM for this crate in two slightly different ways:

### Approach one

https://github.com/stm32-rs/stm32f0xx-hal/tree/features/pwm

This uses the typical approach of initialising the PWM peripheral with the timer and pins to use for PWM. The code is loosely based on https://github.com/stm32-rs/stm32f1xx-hal/blob/master/src/pwm.rs and I can see a number of advantages and disadvantages with this.

Advantages:
* Prevents misconfigurations of timer, channel and GPIO combinations

Disadvantages:
* Does not allow using one channel for multiple GPIOs at once
* Earth shattering number of timer, channel and GPIO combinations need to be encoded
* Someone might want to use PWM without assigned GPIO which is not possible in the current design

### Approach two

https://github.com/stm32-rs/stm32f0xx-hal/tree/features/pwm-alternate

This approach only binds the timer to provide 4 PWM channels without any association to a GPIO.

Advantages:

* Allows for much more flexible configuration of zero or more GPIOs per channel

Disadvantages:

* No sanity checking for correctly configured GPIO pins and channel relations

---

I'm a bit on the fence which variant we should go for. Approach one is rather limiting, especially if we want to support advanced uses of PWM (and maybe other nice timer features). It is also very complex to implement for all chips and all possible combinations at once. On the other hand it would be great to have a way of telling a user that some timer/channel/GPIO combination will not work or is incorrectly configured.

Ideas?

CC @zklapow

### PR DESCRIPTION
**Pull request by jonfin**
Add PWM support based on the stm32f4xx_hal implementation. It is mostly a copy from stm32f4xx_hal with some modification.
Only change to stm32f4xx_hal: it uses the recommended order for setting the register from DM00042534

I did some testing based on a stm32f030c8 chip.

fixes #26

### CODE REVIEW

**Comment by therealprof** [comment]
Thanks for the PR! I've tested it on a STM32F072 and it works a treat. If you could fix the CI issues and register the example with `Cargo.toml` I can merge this in.

**Comment by jonfin** [comment]
It should now work even on more devices. I missed the possibility that there could be other devices than the stm32f030 or stm32f070.

One thing is missing: the PWM implementation for TIM2 (32-bit). I skip it because I cannot test it after changing the calculation of the prescaler / Auto-reload value.

**Comment by therealprof** [comment]
Thanks, it's still missing the example registration in `Cargo.toml`. And if you could squash your PR a bit that'd be much appreciated.

**Comment by jonfin** [comment]
Is the example not automatic registered?

**Comment by therealprof** [comment]
Ah sorry, I missed that it's an example that works on all chips; not used to that. 😅

**Comment by jonfin** [comment]
Me neither ;)
I squashed the commits.

**Review by therealprof — APPROVED** [review]
LGTM, thanks.

bors r+

**Pull request merged**
