### PR TITLE
Fixed PLL multiplier calculation when clocking from HSE

### PR DESCRIPTION
**Pull request by katyo**
Fix for issue #77

### CODE REVIEW

**Comment by pigrew** [comment]
The logic for the "pll source" frequency needs to be modified to not always divide by two. It looks like only the F030 devices predivide HSI by two. In addition, the HSI48 source needs to be accounted for in the devices where it exists.

**Comment by katyo** [comment]
@pigrew Of course, it is little bit more tricky work around that case.

**Comment by therealprof** [comment]
I think this was also addressed by the more comprehensive #87?

**Comment by matoushybl** [comment]
Can we close this PR, @therealprof @katyo?

**Comment by therealprof** [comment]
I think this is superceded. Let's close this then.

**Pull request closed without merging**
