### PR TITLE
RCC: Add ability to use HSE clock source

### PR DESCRIPTION
**Pull request by zklapow**
This adds a `clock_src` param to the `CFGR` builder and the accompanying code to enable the `HSE` clock in `freeze`. This supports using the HSE both by itself and as input to the PLL and can be used by simply adding a `.hse` call like so:

```rust
        let clocks = rcc.cfgr.hse(16.mhz()).sysclk(32.mhz()).freeze();
```

### CODE REVIEW

**Comment by therealprof** [comment]
@zklapow Thanks a lot for your contribution. This looks like a very nice addition. I'm not sure what the CI build issue is but I'm actually getting the same error locally after applying your PR. Also I think this will clash quite heavily with #17 so I'd like to ask you to rework your PR when this has landed.

**Comment by david-sawatzke** [comment]
The issue is the empty `repro_hardfault.rs` file, where the `#[no_std]` is missing, so rust tries to compile it with std.

**Comment by HarkonenBade** [comment]
> The issue is the empty `repro_hardfault.rs` file, where the `#[no_std]` is missing, so rust tries to compile it with std.

Nice catch!

**Comment by zklapow** [comment]
sorry about that, did not intend to commit that file should be gone now.

@therealprof I saw that and figured as much 👍 but figured it was worth submitting this early anyhow. On that note I am working on some other things for this hal (pwm support is the big one) should I create issues for those things or just submit PRs when ready?

**Comment by therealprof** [comment]
@zklapow Ping?

**Comment by zklapow** [comment]
just pushed an update that should work with the new changes

**Comment by zklapow** [comment]
👍 done

**Pull request merged**
